# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/belnask/OneDrive - Reed Elsevier Group ICO Reed Elsevier Inc/Desktop/PROJECT/2026/02 SMD  REQUEST/index.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 640)
        MainWindow.setMinimumSize(QtCore.QSize(450, 640))
        MainWindow.setMaximumSize(QtCore.QSize(450, 640))
        MainWindow.setStyleSheet("QWidget#root {\n"
"    background: #232323;\n"
"    color: white;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 10px;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QFrame#card {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#title {\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"    color: #f3f3f3;\n"
"}\n"
"\n"
"QLabel#subtitle {\n"
"    font-size: 11px;\n"
"    color: #999999;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px 16px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QPushButton#autoBtn,\n"
"QPushButton#checkBtn {\n"
"    background: #006986;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#autoBtn:hover,\n"
"QPushButton#checkBtn:hover {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #ad59ff, stop:1 #ff4960\n"
"    );\n"
"}\n"
"\n"
"QPushButton#macMinBtn,\n"
"QPushButton#macCloseBtn,\n"
"QPushButton#devCloseBtn {\n"
"    border-radius: 10px;\n"
"    font-size: 11px;\n"
"    font-weight: 900;\n"
"    padding: 0px;\n"
"    color: rgba(0, 0, 0, 0.72);\n"
"}\n"
"\n"
"QPushButton#macMinBtn {\n"
"    background: #f5c542;\n"
"}\n"
"\n"
"QPushButton#macMinBtn:hover {\n"
"    background: #ffd45c;\n"
"}\n"
"\n"
"QPushButton#macCloseBtn,\n"
"QPushButton#devCloseBtn {\n"
"    background: #ff5f57;\n"
"}\n"
"\n"
"QPushButton#macCloseBtn:hover,\n"
"QPushButton#devCloseBtn:hover {\n"
"    background: #ff7b74;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: rgba(255, 255, 255, 0.08);\n"
"    color: rgba(255,255,255,0.35);\n"
"}\n"
"\n"
"QFrame#statusFrame {\n"
"    background: rgba(255, 255, 255, 0.07);\n"
"    border: 1px solid rgba(255,255,255,0.10);\n"
"    border-radius: 15px;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
"QLabel#statusText {\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    color: rgba(255,255,255,0.92);\n"
"}\n"
"\n"
"QLabel#dot {\n"
"    background: #32d98a;\n"
"    border-radius: 10px;\n"
"    min-width: 20px;\n"
"    min-height: 20px;\n"
"    max-width: 20px;\n"
"    max-height: 20px;\n"
"}\n"
"\n"
"QFrame#logShell {\n"
"    background: rgba(255, 255, 255, 0.05);\n"
"    border: 1px solid rgba(255,255,255,0.08);\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QLabel#sectionTitle {\n"
"    font-size: 12px;\n"
"    font-weight: 700;\n"
"    color: rgba(255,255,255,0.84);\n"
"}\n"
"\n"
"QPlainTextEdit#logViewer {\n"
"    background: rgba(255, 255, 255, 0.04);\n"
"    border: 1px solid rgba(255,255,255,0.08);\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"    color: rgba(255,255,255,0.92);\n"
"    selection-background-color: rgba(155, 61, 255, 0.35);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: rgba(255, 255, 255, 0.04);\n"
"    border: 1px solid rgba(255,255,255,0.08);\n"
"    border-radius: 12px;\n"
"    padding: 10px 12px;\n"
"    color: rgba(255,255,255,0.92);\n"
"    selection-background-color: rgba(155, 61, 255, 0.35);\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QPlainTextEdit#logViewer:focus {\n"
"    border: 1px solid rgba(0, 132, 168, 0.75);\n"
"}\n"
"\n"
"QCheckBox#extraCourtRequestCheck,\n"
"QCheckBox#networkDropCheck,\n"
"QCheckBox#sendEmailCheck {\n"
"    color: #f3f3f3;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    spacing: 10px;\n"
"}\n"
"\n"
"QCheckBox#extraCourtRequestCheck::indicator,\n"
"QCheckBox#networkDropCheck::indicator,\n"
"QCheckBox#sendEmailCheck::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 1px solid rgba(255,255,255,0.35);\n"
"    background: rgba(255,255,255,0.06);\n"
"}\n"
"\n"
"QCheckBox#extraCourtRequestCheck::indicator:checked,\n"
"QCheckBox#networkDropCheck::indicator:checked,\n"
"QCheckBox#sendEmailCheck::indicator:checked {\n"
"    background: #32d98a;\n"
"    border: 1px solid #32d98a;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 8px;\n"
"    margin: 4px 2px 4px 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(255,255,255,0.18);\n"
"    border-radius: 4px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(255,255,255,0.28);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
"\n"
"QMessageBox {\n"
"    background-color: #232323;\n"
"}\n"
"\n"
"QMessageBox QLabel {\n"
"    color: #f3f3f3;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QMessageBox QPushButton {\n"
"    background: #006986;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 8px 14px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QMessageBox QPushButton:hover {\n"
"    background: #0084a8;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.root = QtWidgets.QWidget(self.centralwidget)
        self.root.setObjectName("root")
        self.root_layout = QtWidgets.QVBoxLayout(self.root)
        self.root_layout.setContentsMargins(12, 12, 12, 12)
        self.root_layout.setSpacing(16)
        self.root_layout.setObjectName("root_layout")
        self.card = QtWidgets.QFrame(self.root)
        self.card.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.card.setObjectName("card")
        self.layout_card = QtWidgets.QVBoxLayout(self.card)
        self.layout_card.setContentsMargins(0, 0, 0, 0)
        self.layout_card.setSpacing(14)
        self.layout_card.setObjectName("layout_card")
        self.header_bar = QtWidgets.QFrame(self.card)
        self.header_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header_bar.setObjectName("header_bar")
        self.header_layout = QtWidgets.QHBoxLayout(self.header_bar)
        self.header_layout.setContentsMargins(0, 0, 0, 0)
        self.header_layout.setSpacing(0)
        self.header_layout.setObjectName("header_layout")
        self.window_btn_wrap = QtWidgets.QWidget(self.header_bar)
        self.window_btn_wrap.setMinimumSize(QtCore.QSize(60, 0))
        self.window_btn_wrap.setMaximumSize(QtCore.QSize(60, 16777215))
        self.window_btn_wrap.setObjectName("window_btn_wrap")
        self.window_btn_row = QtWidgets.QHBoxLayout(self.window_btn_wrap)
        self.window_btn_row.setContentsMargins(0, 0, 0, 0)
        self.window_btn_row.setSpacing(8)
        self.window_btn_row.setObjectName("window_btn_row")
        self.macCloseBtn = QtWidgets.QPushButton(self.window_btn_wrap)
        self.macCloseBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.macCloseBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.macCloseBtn.setObjectName("macCloseBtn")
        self.window_btn_row.addWidget(self.macCloseBtn)
        self.macMinBtn = QtWidgets.QPushButton(self.window_btn_wrap)
        self.macMinBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.macMinBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.macMinBtn.setObjectName("macMinBtn")
        self.window_btn_row.addWidget(self.macMinBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.window_btn_row.addItem(spacerItem)
        self.header_layout.addWidget(self.window_btn_wrap)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_layout.addItem(spacerItem1)
        self.title_wrap = QtWidgets.QWidget(self.header_bar)
        self.title_wrap.setObjectName("title_wrap")
        self.title_layout = QtWidgets.QVBoxLayout(self.title_wrap)
        self.title_layout.setContentsMargins(0, 0, 0, 0)
        self.title_layout.setSpacing(0)
        self.title_layout.setObjectName("title_layout")
        self.title = QtWidgets.QLabel(self.title_wrap)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.title_layout.addWidget(self.title)
        self.subtitle = QtWidgets.QLabel(self.title_wrap)
        self.subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle.setObjectName("subtitle")
        self.title_layout.addWidget(self.subtitle)
        self.header_layout.addWidget(self.title_wrap)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_layout.addItem(spacerItem2)
        self.header_right_spacer = QtWidgets.QWidget(self.header_bar)
        self.header_right_spacer.setMinimumSize(QtCore.QSize(60, 0))
        self.header_right_spacer.setMaximumSize(QtCore.QSize(60, 16777215))
        self.header_right_spacer.setObjectName("header_right_spacer")
        self.header_layout.addWidget(self.header_right_spacer)
        self.layout_card.addWidget(self.header_bar)
        self.statusFrame = QtWidgets.QFrame(self.card)
        self.statusFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusFrame.setObjectName("statusFrame")
        self.status_layout = QtWidgets.QHBoxLayout(self.statusFrame)
        self.status_layout.setContentsMargins(12, 10, 12, 10)
        self.status_layout.setSpacing(10)
        self.status_layout.setObjectName("status_layout")
        self.dot = QtWidgets.QLabel(self.statusFrame)
        self.dot.setMinimumSize(QtCore.QSize(20, 20))
        self.dot.setMaximumSize(QtCore.QSize(20, 20))
        self.dot.setText("")
        self.dot.setObjectName("dot")
        self.status_layout.addWidget(self.dot)
        self.statusText = QtWidgets.QLabel(self.statusFrame)
        self.statusText.setObjectName("statusText")
        self.status_layout.addWidget(self.statusText)
        self.layout_card.addWidget(self.statusFrame)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.sectionTitle_template = QtWidgets.QLabel(self.card)
        self.sectionTitle_template.setObjectName("sectionTitle_template")
        self.gridLayout.addWidget(self.sectionTitle_template, 0, 0, 1, 2)
        self.template_edit = QtWidgets.QLineEdit(self.card)
        self.template_edit.setObjectName("template_edit")
        self.gridLayout.addWidget(self.template_edit, 1, 0, 1, 1)
        self.autoBtn_browse = QtWidgets.QPushButton(self.card)
        self.autoBtn_browse.setObjectName("autoBtn_browse")
        self.gridLayout.addWidget(self.autoBtn_browse, 1, 1, 1, 1)
        self.sectionTitle_output = QtWidgets.QLabel(self.card)
        self.sectionTitle_output.setObjectName("sectionTitle_output")
        self.gridLayout.addWidget(self.sectionTitle_output, 2, 0, 1, 2)
        self.subtitle_output_note = QtWidgets.QLabel(self.card)
        self.subtitle_output_note.setWordWrap(True)
        self.subtitle_output_note.setObjectName("subtitle_output_note")
        self.gridLayout.addWidget(self.subtitle_output_note, 3, 0, 1, 2)
        self.subtitle_extra_note = QtWidgets.QLabel(self.card)
        self.subtitle_extra_note.setWordWrap(True)
        self.subtitle_extra_note.setObjectName("subtitle_extra_note")
        self.gridLayout.addWidget(self.subtitle_extra_note, 4, 0, 1, 2)
        self.extraCourtRequestCheck = QtWidgets.QCheckBox(self.card)
        self.extraCourtRequestCheck.setObjectName("extraCourtRequestCheck")
        self.gridLayout.addWidget(self.extraCourtRequestCheck, 5, 0, 1, 2)
        self.subtitle_network_note = QtWidgets.QLabel(self.card)
        self.subtitle_network_note.setWordWrap(True)
        self.subtitle_network_note.setObjectName("subtitle_network_note")
        self.gridLayout.addWidget(self.subtitle_network_note, 6, 0, 1, 2)
        self.networkDropCheck = QtWidgets.QCheckBox(self.card)
        self.networkDropCheck.setObjectName("networkDropCheck")
        self.gridLayout.addWidget(self.networkDropCheck, 7, 0, 1, 2)
        self.subtitle_email_note = QtWidgets.QLabel(self.card)
        self.subtitle_email_note.setWordWrap(True)
        self.subtitle_email_note.setObjectName("subtitle_email_note")
        self.gridLayout.addWidget(self.subtitle_email_note, 8, 0, 1, 2)
        self.sendEmailCheck = QtWidgets.QCheckBox(self.card)
        self.sendEmailCheck.setObjectName("sendEmailCheck")
        self.gridLayout.addWidget(self.sendEmailCheck, 9, 0, 1, 2)
        self.layout_card.addLayout(self.gridLayout)
        self.button_row = QtWidgets.QHBoxLayout()
        self.button_row.setObjectName("button_row")
        self.autoBtn_generate = QtWidgets.QPushButton(self.card)
        self.autoBtn_generate.setMinimumSize(QtCore.QSize(0, 42))
        self.autoBtn_generate.setObjectName("autoBtn_generate")
        self.button_row.addWidget(self.autoBtn_generate)
        self.autoBtn_viewFolder = QtWidgets.QPushButton(self.card)
        self.autoBtn_viewFolder.setMinimumSize(QtCore.QSize(0, 42))
        self.autoBtn_viewFolder.setObjectName("autoBtn_viewFolder")
        self.button_row.addWidget(self.autoBtn_viewFolder)
        self.layout_card.addLayout(self.button_row)
        self.logShell = QtWidgets.QFrame(self.card)
        self.logShell.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logShell.setObjectName("logShell")
        self.log_layout = QtWidgets.QVBoxLayout(self.logShell)
        self.log_layout.setContentsMargins(12, 12, 12, 12)
        self.log_layout.setSpacing(8)
        self.log_layout.setObjectName("log_layout")
        self.sectionTitle_log = QtWidgets.QLabel(self.logShell)
        self.sectionTitle_log.setObjectName("sectionTitle_log")
        self.log_layout.addWidget(self.sectionTitle_log)
        self.logViewer = QtWidgets.QPlainTextEdit(self.logShell)
        self.logViewer.setReadOnly(True)
        self.logViewer.setObjectName("logViewer")
        self.log_layout.addWidget(self.logViewer)
        self.layout_card.addWidget(self.logShell)
        self.root_layout.addWidget(self.card)
        self.verticalLayout.addWidget(self.root)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SMD Bulk Collection Request Tool"))
        self.macCloseBtn.setText(_translate("MainWindow", "✕"))
        self.macMinBtn.setText(_translate("MainWindow", "—"))
        self.title.setText(_translate("MainWindow", "SMD Bulk Collection Request Tool"))
        self.subtitle.setText(_translate("MainWindow", "Court & Counsel Bulk Collection Request Tool"))
        self.statusText.setText(_translate("MainWindow", "Ready"))
        self.sectionTitle_template.setText(_translate("MainWindow", "Template File"))
        self.template_edit.setPlaceholderText(_translate("MainWindow", "Select the SMD Appeals Template (.xlsx or .xlsm)"))
        self.autoBtn_browse.setText(_translate("MainWindow", "Browse..."))
        self.sectionTitle_output.setText(_translate("MainWindow", "Output Folders"))
        self.subtitle_output_note.setText(_translate("MainWindow", "Created automatically beside the selected template file:\n"
"CNL-{COUNSEL_FOLDER}\n"
"CT-{COURT_FOLDER}"))
        self.subtitle_extra_note.setText(_translate("MainWindow", "Creates a new CT request template"))
        self.extraCourtRequestCheck.setText(_translate("MainWindow", "Create new request template"))
        self.subtitle_network_note.setText(_translate("MainWindow", "Automatically copy generated files to the designated network path"))
        self.networkDropCheck.setText(_translate("MainWindow", "Auto-drop to network path"))
        self.subtitle_email_note.setText(_translate("MainWindow", "Send the completion email after all processing is done"))
        self.sendEmailCheck.setText(_translate("MainWindow", "Send completion email (works only in Classic Outlook)"))
        self.autoBtn_generate.setText(_translate("MainWindow", "Generate Files"))
        self.autoBtn_viewFolder.setText(_translate("MainWindow", "View Folder"))
        self.sectionTitle_log.setText(_translate("MainWindow", "Activity Log"))
        self.logViewer.setPlaceholderText(_translate("MainWindow", "Status messages will appear here."))
